language: scala

scala:
  - "0.22.0-bin-20200123-9982f0d-NIGHTLY"
  - "2.12.10"
  - "2.13.1"

jdk:
  - openjdk11

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

script:
  - if [[ "$TRAVIS_SCALA_VERSION" == 0.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION coreJVM/test;
    else
      sbt ++$TRAVIS_SCALA_VERSION fmtCheck test mimaReportBinaryIssues;
    fi

