language: scala

scala:
  - "2.12.10"
  - "2.13.1"

jdk:
  - openjdk11

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION fmtCheck
  - sbt ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues

