language: scala

scala:
  - "2.10.7"
  - "2.11.12"
  - "2.12.8"
  - "2.13.0"

jdk:
  - openjdk11

sudo: required
dist: trusty

before_install:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION fmtCheck
  - sbt ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues

