sudo: required
dist: trusty
before_install:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

language: scala

scala:
  - "2.10.7"
  - "2.11.12"
  - "2.12.8"
  - "2.13.0-RC2"

jdk:
  - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -exec rm {} +
  - find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} +
