sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

language: scala

scala:
  - "2.10.6"
  - "2.11.8"
  - "2.12.1"

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test mima-report-binary-issues

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -exec rm {} +
  - find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} +

matrix:
  include:
  - sudo: required
    dist: trusty
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.1/bin/travis_setup.sh | bash -x
    script:
    - sbt nativeTest/run
